export enum HomePageActionTypes {
    START_GAME = 'START_GAME',
    REVEAL_TILE = 'REVEAL_TILE',
    SET_GAME_WON = 'SET_GAME_WON',
    SET_GAME_LOST = 'SET_GAME_LOST',
    SET_GAME_WAITING = 'SET_GAME_WAITING',
    MARK_TILE = 'MARK_TILE',
    SEND_SCORE_BEGIN = 'SEND_SCORE_BEGIN',
    SEND_SCORE_SUCCESS = 'SEND_SCORE_SUCCESS',
    SEND_SCORE_FAILURE = 'SEND_SCORE_FAILURE'
};